import turtle

sc = turtle.Screen()
sc.bgcolor("orange")
sc.title("برنامه من")
sc.setup(600, 400)

t = turtle.Turtle()
t.shape("classic")
t.shapesize(3)
t.color("red")
t.pencolor("blue")
t.pensize(4)
t.write(1, font=("Arial", 22))
t.forward(50)
t.write(2, font=("Arial", 22))
t.forward(50)
t.write(3, font=("Arial", 22))
t.forward(50)
t.write(4, font=("Arial", 22))
t.forward(50)
t.write(5, font=("Arial", 22))
t.forward(50)
t.stamp()
t.home()
t.left(90)
t.write(1, font=("Arial", 22))
t.forward(50)
t.write(2, font=("Arial", 22))
t.forward(50)
t.write(3, font=("Arial", 22))
t.forward(50)
t.write(4, font=("Arial", 22))
t.forward(50)
t.stamp()

turtle.done()